### ISSUE TITLE
ITP: dtkcore

### ISSUE THREAD

**Issue by YanhaoMo** [debiancn/repo#100]
包名: dtkcore
版本: 0.1.0
URL: https://github.com/linuxdeepin/dtkcore/tree/0.1.0

**Comment by YanhaoMo** [comment]
完成,以入库.

**Comment by hosiet** [comment]
还没看具体内容，不过切记注意文件与重构前的包是否存在冲突。

**Comment by YanhaoMo** [comment]
目前, 仓库的包应该还没有依赖dtkcore的, 也就是说这个包目前还没有安装的必要, 所以有冲突也没有关系吧,

**Comment by YanhaoMo** [comment]
看了一下, 应该没有与目前的包冲突, 目前的包安装在/usr/include/libdtk-1.0下, 这个包安装在/usr/include/libdtk-1.2下
