### ISSUE TITLE
ITP: gsettings-qt

### ISSUE THREAD

**Issue by YanhaoMo** [debiancn/repo#102]
包名: gsettings-qt
URL: https://launchpad.net/gsettings-qt

**Comment by hosiet** [comment]
快打包，打得出来算我输（

**Comment by YanhaoMo** [comment]
萌新瑟瑟发抖 ><

**Comment by YanhaoMo** [comment]
蛋疼的是我在deepin下试了打包是没有问题的, 换到debian下就不行
不知道ubuntu下怎么样, 实在不行要不给个patch去掉这个test - -

**Comment by YanhaoMo** [comment]
先上传两个deeepin拿来的包:
libgsettings-qt1_0.1+16.04.20160329-1_amd64.deb
libgsettings-qt-dev_0.1+16.04.20160329-1_amd64.deb
用来编译 dtkwidget
然后等上游解决bug https://bugs.launchpad.net/gsettings-qt/+bug/1706682

**Comment by hosiet** [comment]
已经做好了，而且在官方源推到了 NEW 队列。
