### ISSUE TITLE
RFP: BOOKWORM阅读器

### ISSUE THREAD

**Issue by jing2uo** [debiancn/repo#103]
BOOKWORM
官网：
https://babluboy.github.io/bookworm/
协议：GPL3
项目主页：
https://github.com/babluboy/bookworm
简介：
电子书，支持pdf，mobi，epub，Linux下为数不多支持mobi格式的阅读器噢。

**Comment by hosiet** [comment]
https://tracker.debian.org/pkg/bookworm
