### ISSUE TITLE
RFP: peek，gif录制工具

### ISSUE THREAD

**Issue by hipkomh** [debiancn/repo#104]
peek

项目主页：https://github.com/phw/peek
项目协议：GPL3

录制gif图片，使用简单，图片质量很不错

**Comment by yangfl** [comment]
forwarded https://github.com/phw/peek/issues/78

**Comment by hosiet** [comment]
这个我比较感兴趣，接了（

**Comment by hosiet** [comment]
https://salsa.debian.org/hosiet-guest/peek
