### ISSUE TITLE
RFP: Persepolis，一个基于aria2c的python实现的下载工具

### ISSUE THREAD

**Issue by JackieMium** [debiancn/repo#106]
[官网](https://persepolisdm.github.io/)介绍：
> Persepolis Is A Download Manager And A GUI For Aria2 Which Is Powered By Python. Persepolis Is A Sample Of Free And Open Source Software And Developed For GNU/Linux Distributions,BSDs,Mac OS and Windows. You Can Join Persepolis Users And Help Us With Developing It.

项目地址：https://github.com/persepolisdm/persepolis
PPA可以直接下载到deb包：https://launchpad.net/~persepolis
我在sid上装需要的依赖有：libqt5designer5 libqt5help5 libqt5sql5 libqt5sql5-sqlite libqt5test5 persepolis python3-pyqt5 python3-setproctitle python3-sip

**Comment by yangfl** [comment]
代码质量堪忧，2.5好一点，等上游放tag
