### ISSUE TITLE
RFP: vala-panel-appmenu

### ISSUE THREAD

**Issue by hosxy** [debiancn/repo#109]
简介：一个支持 xfce mate budgie 桌面的全局菜单(global menu)插件
项目地址：https://github.com/rilian-la-te/vala-panel-appmenu
协议： GPL V3

**Comment by yangfl** [comment]
https://github.com/rilian-la-te/vala-panel-appmenu/issues/130 关切中

**Comment by hipkomh** [comment]
这个官方源里有了，至少进了sid。可以关掉的

**Comment by YanhaoMo** [comment]
testing里也有了
