### ISSUE TITLE
社区源中baidupcs出现timeout的错误

### ISSUE THREAD

**Issue by lq95v5** [debiancn/repo#114]
Download slice failed, retry delay 10 second, tid: 0x7f46e77be700. message: Timeout was reached:XXXX

而我自己打包的baidupcs，不会出现timeout的错误，这个timeout影响下载速度- -
建议移除baidupcs，因为每次我使用自己打包的pcs，apt upgrade之后就会被社区源的baidupcs替换。。
所以说不是很方便。
我自己打包的baidupcs我放到Debiancn群里面了

**Comment by hosiet** [comment]
请现在测试一下，更新了 Stretch 和 Buster/Sid 中的软件。

**Comment by hosiet** [comment]
已解决
