### ISSUE TITLE
RFS: crossover

### ISSUE THREAD

**Issue by FindHao** [debiancn/repo#115]
* 包名 : crossover
  版本 : 连接自动更新稳定版，目前16
  作者 : codeweavers
* 主页 : codeweavers.com
* 协议 : 专有
  语言 :blob
  简介 : linux平台下运行win程序，基于wine提供容器解决方案。

deb包地址：
http://crossover.codeweavers.com/redirect/crossover.deb

**Comment by YanhaoMo** [comment]
这个需要授权吧

**Comment by YanhaoMo** [comment]
没用过这个, 想请解释一下, 这是是安装之后使用时需要授权还是安装就需要授权, 另外这个软件是否允许第三方分发

**Comment by FindHao** [comment]
@YanhaoMo 软件试用期两个周。到期后需要购买。第三方分发的问题，我去问问。

**Comment by FindHao** [comment]
官方回复允许第三方不修改包的分发。arch好像已经收录了。

**Comment by yangfl** [comment]
aur是自己编译包，所以怎么弄都没问题。
debian的话怎么都会改一下.deb，怕是不行，要么就只能installer了。

**Comment by yangfl** [comment]
还有自动更新？这肯定有问题啊

**Comment by FindHao** [comment]
@yangfl  什么意思？什么自动更新？我是说连接是一个redirection，会自动跳转最新稳定版的下载。

**Comment by yangfl** [comment]
软件源不是这样工作的，不会跟随URL跳转。
其实不允许修改包才最要紧。对于不允许修改的包进各种源都麻烦。

**Comment by FindHao** [comment]
@yangfl  但是软件源跟url跳转关系我没明白。既然url可以自动跳转，那就定期抓下来对比，然后push到源上去就行啊。
第二个问题我就不清楚了。soga

**Comment by yangfl** [comment]
软件源是需要手动更新的。
anyway， 找菊苣来具体看一下吧 @YanhaoMo

**Comment by yangfl** [comment]
done
