### ISSUE TITLE
RFS: typora

### ISSUE THREAD

**Issue by FindHao** [debiancn/repo#116]
* 包名 : typora
  版本 : v0.9.38
  作者 : https://twitter.com/LeeAbner （中国人）  or https://twitter.com/Typora
* 主页 : https://typora.io/
* 协议 : 没找到官网明确说明，但其credits里说明的其使用的大多数包都是MIT license。
  语言 : blob
  简介 : 功能强大的markdown编辑器，即写即看。

官方安装方法：
http://support.typora.io/Typora-on-Linux/
但debian在更新时，需设置源为
```shell
deb https://typora.io/linux ./
```
其更新时，下载包的路径有问题。

建议收录。

**Comment by hosiet** [comment]
typora 官方提供的源我正在使用，没发现什么问题。

鉴于官方源可用，我不太希望进行收录。

**Comment by FindHao** [comment]
@hosiet debian下更新时，会提示下载的路径不对，因为使用上面的源更新，会导致下载链接变为`https://typora.io/linux/linux/typora_0.9.38.deb` 。需要手动下载包更新。

**Comment by hosiet** [comment]
具体错误是什么？给个截图可否？

我按照官网的指南来做是没有问题的。

**Comment by FindHao** [comment]
@hosiet 
debian 9 x86 
```shell
$ sudo apt install typora
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
下列【新】软件包将被安装：
  typora
升级了 0 个软件包，新安装了 1 个软件包，要卸载 0 个软件包，有 0 个软件包未被升级。
需要下载 43.5 MB 的归档。
解压缩后会消耗 157 MB 的额外空间。
错误:1 https://typora.io/linux ./ typora 0.9.38-1
  404  Not Found
E: 无法下载 https://typora.io/linux/./linux/typora_0.9.38_amd64.deb  404  Not Found
E: 有几个软件包无法下载，要不运行 apt-get update 或者加上 --fix-missing 的选项再试试？
```

**Comment by FindHao** [comment]
只能手动去掉中间的`./linux`为
`https://typora.io/linux/typora_0.9.38_amd64.deb`下载deb包安装。

**Comment by hosiet** [comment]
你需要更新你的 sources.list 行，严格按照官方的写法来。

**Comment by FindHao** [comment]
官方的写法有warning：
```shell
正在读取软件包列表... 完成
W: 冲突的发行版：https://typora.io ./linux/ InRelease (期望 ./linux/ 但得到 )
E: 无法下载 https://typora.io/./linux/InRelease  在 Release 文件中找不到期望的条目 Sources（sources.list条目有误，或者文件有误）
E: 部分索引文件下载失败。如果忽略它们，那将转而使用旧的索引文件。
```
尽管可以下载。。

**Comment by FindHao** [comment]
https://github.com/typora/typora-issues/issues/331
