### ISSUE TITLE
RFS: overture

### ISSUE THREAD

**Issue by simonsmh** [debiancn/repo#117]
https://github.com/shawn1m/overture

**Comment by simonsmh** [comment]
https://app.simonsmh.cc/files/overture_1.3.6~rc2-1_amd64.deb

**Comment by yangfl** [comment]
* 为什么关test？
* no clean编译两次会失败 `dpkg-buildpackage -b -us -uc -nc`

**Comment by simonsmh** [comment]
- 因为不会修test（
- 不会改二进制文件名称，不会用dh-exec什么的（（

**Comment by yangfl** [comment]
🔫🌚
