### ISSUE TITLE
RFP：Firefox Release ( Not ESR)

### ISSUE THREAD

**Issue by hosxy** [debiancn/repo#119]
* 包名 :  Firefox
  版本 :  Relaese
  作者 :  Mozilla
* 主页 :  https://www.mozilla.org
* 协议 :  MPL (Mozilla Public License)
  语言 :  C++ / rust

stable 和 testing 源里没有 release 只有 ESR。而且 ESR 版本更新太慢，很多新技术没法第一时间体验到。

**Comment by hosiet** [comment]
http://mozilla.debian.net

Rust 的问题很麻烦，所以非 esr 版暂时是无法构建的。
