### ISSUE TITLE
RFP：ieaseMusic 播放器

### ISSUE THREAD

**Issue by hipkomh** [debiancn/repo#121]
* 包名 : ieaseMusic
  版本 : v1.0.6
  作者 : trazyn
* 主页 : https://github.com/trazyn/ieaseMusic 
* 协议 : GPLv2+ / GPLv3+ / BSD / 专有
  语言 : C / C++ / blob  // blob=上游仅提供二进制文件
  简介 : 最好看的网易云播放器，没有依赖！

**Comment by yangfl** [comment]
又是Electron🌚，使用上游包了

**Comment by hipkomh** [comment]
这位大大还写了wewechat，质量也蛮高的 ~ 要不要一起收了

**Comment by yangfl** [comment]
Electron也叫好？￼￼🌚窝对前端的偏见又加了一分
