### ISSUE TITLE
RFP:BaiduPCS 百度网盘命令行工具

### ISSUE THREAD

**Issue by Z-Y00** [debiancn/repo#127]
* 包名 : 百度网盘命令行工具
  版本 : 0.3.1
  作者 : GangZhuo
* 主页 : https://github.com/GangZhuo/BaiduPCS

**Comment by hosiet** [comment]
http://repo.debiancn.org/pool/main/b/baidupcs/baidupcs_0.3.1+git20170908-1_amd64.deb

貌似以前就有。
