### ISSUE TITLE
RFP: flameshot

### ISSUE THREAD

**Issue by hosxy** [debiancn/repo#128]
包名 : flameshot
作者 : lupoDharkael
主页 : https://github.com/lupoDharkael/flameshot
协议 : GPLv3
语言 :  C++
简介 :  一个很强大的截图软件，个人感觉堪比深度截图，同样也是用 QT 写的。

**Comment by hosiet** [comment]
这个不错，锅我接了。

https://bugs.debian.org/886409

**Comment by hosiet** [comment]
http://repo.debiancn.org/pool/main/f/flameshot/
