### ISSUE TITLE
RFP：xfce4-statusnotifier-plugin

### ISSUE THREAD

**Issue by hosxy** [debiancn/repo#129]
包名 : xfce4-statusnotifier-plugin
 版本 : 0.2.1
 作者 : ninetls  / xfce desktop
 主页 : https://git.xfce.org/panel-plugins/xfce4-statusnotifier-plugin/ or  https://github.com/xfce-mirror/xfce4-statusnotifier-plugin
 协议 : GPLv2
 语言 : C 
 简介 : xfce4-panel 的通知区域插件，比 xfce4-panel 自带的通知区域功能强大很多，这是 xfce 的官方项目，不知道为什么 debian 没有收录
![xfce](http://goodies.xfce.org/_media/projects/panel-plugins/sn-configuration.png?cache=) ![xfce](http://goodies.xfce.org/_media/projects/panel-plugins/sn-plugin.png?cache=)

**Comment by hosiet** [comment]
https://bugs.debian.org/891237

已转发至 Debian 官方的 wnpp

**Comment by hosiet** [comment]
已上传至 Debian 官方源。稍后计划推送进入 stretch-backports。
