### ISSUE TITLE
RFP: vocal

### ISSUE THREAD

**Issue by lowy** [debiancn/repo#137]
包名 : vocal
版本 : 2.1.6
作者 : nathandyer
主页 : https://github.com/needle-and-thread/vocal
协议 : GPLv3+
语言 :  Vala 
简介 : The podcast client for the modern free desktop.

**Comment by lowy** [comment]
源码包提供deb打包支持 不过要把debian/control里不存在的 libunity-dev 依赖划掉

**Comment by hosiet** [comment]
完成（Debian Buster）

Debian Stretch 里缺一些依赖包需要更多工作，有需要的话再说一下

**Comment by hosiet** [comment]
由于上游已停止开发 https://nathandyer.me/2024/11/26/end-of-vocal.html ，相关软件包已清理。
