### ISSUE TITLE
lilydict 依赖缺失，无法启动

### ISSUE THREAD

**Issue by songww** [debiancn/repo#138]
lilydict依赖的部分qt组件没有自动安装
![default](https://user-images.githubusercontent.com/8115960/37891776-1a8177ec-3108-11e8-8ad5-eca5e32b986c.png)

**Comment by hosiet** [comment]
手动添加了 qml 的依赖，应该解决了问题。请测试一下。

**Comment by songww** [comment]
![default](https://user-images.githubusercontent.com/8115960/38194159-6923c788-36a8-11e8-9018-0517fc380844.png)
依然缺失很多东西

**Comment by songww** [comment]
手动安装了`qml-module-qtquick-controls`
命令行有如下输出:
QString::arg: 1 argument(s) missing in 无法解析%2中的符号“%2”：%3

界面很是奇怪:
![default](https://user-images.githubusercontent.com/8115960/38194342-8e098a28-36a9-11e8-84f8-fc4866cd9bad.png)

**Comment by lowy** [comment]
我这里还算正常 虽然有道跟语音的部分废了
![2018-04-06_11 38 26](https://user-images.githubusercontent.com/6565177/38402522-6d3b131e-398f-11e8-8ab6-e631b5b20bc1.png)

**Comment by hosiet** [comment]
考虑到上游项目 https://github.com/suziwen/lilydict 已7年无更新，暂不考虑修复相关问题。
