### ISSUE TITLE
libqtshadowsocks2 依赖问题

### ISSUE THREAD

**Issue by FlyGoat** [debiancn/repo#141]
Testing 下 libshadowsocks2 的依赖 libbotan-1.10-1 不存在
提示
`libqtshadowsocks2 : 依赖: libbotan-1.10-1 (>= 1.10.12) 但无法安装它`
望修复，谢谢。

**Comment by hosiet** [comment]
botan1.10 马上就要退出历史舞台了，稍后会用 botan 新版本处理 ss-qt5.

**Comment by hosiet** [comment]
已处理，待三天后 testing 中 qrencode 升级为 4.0+ 版本后可解决问题。
