### ISSUE TITLE
RFP: pulseeffects

### ISSUE THREAD

**Issue by jing2uo** [debiancn/repo#142]
* 包名 : pulseeffects
  版本 : v3.2.1
  作者 : wwmm
* 主页 : https://github.com/wwmm/pulseeffects/releases
* 协议 : GPLv3+
  语言 : python
  简介 : 均衡器

ubuntu的ppa里有，但不喜欢加那个。
试了下感觉效果还不错，cn源能不能加~

**Comment by hosiet** [comment]
https://ftp-master.debian.org/new/pulseeffects_4.5.6-2.html

**Comment by hosiet** [comment]
由于新版需要 boost 1.65+，所以暂时不兼容 Debian 9。
