### ISSUE TITLE
New upstream release of shadowsocks-qt5

### ISSUE THREAD

**Issue by Z-Y00** [debiancn/repo#150]
Hi,
@hosiet ,the packages for shadowsocks need update
thanks a lot

**Comment by Z-Y00** [comment]
Also, can you please pack the https://github.com/shadowsocks/simple-obfs
thanks a lot

**Comment by hosiet** [comment]
@Z-Y00 I believe shadowsocks in testing and unstable is pretty up-to-date. Are you referring to shadowsocks in stretch?

**Comment by Z-Y00** [comment]
no, shadowsocks-qt5 I mean, which has only been packed by you, and only exits in debiancn's mirror

**Comment by hosiet** [comment]
shadowsocks-qt5 的 Unstable / Sid 仓库版本已正常更新，Testing 用户需要再等三天等新版 qrencode 4.0+ 进入软件源后才能正常使用。如需更新 Stretch 对应的版本请重开 issue 表明。
