### ISSUE TITLE
RFS: mtproxy 

### ISSUE THREAD

**Issue by simonsmh** [debiancn/repo#154]
mtproxy
https://github.com/simonsmh/MTProxy
Closes #148

**Comment by simonsmh** [comment]
https://app.simonsmh.cc/files/mtproxy_1.0-1_amd64.deb

**Comment by Yanhao** [comment]
官方源已经有，不再考虑打包

**Comment by simonsmh** [comment]
官方源哪有啊，有链接吗？
社区源里确实是有，我加了systemd service方便使用。

Yanhao <notifications@github.com> 於 2019年1月11日 週五 下午2:47寫道：

**Comment by Yanhao** [comment]
看错了，把社区源里的看成官方源了

**Comment by Yanhao** [comment]
done
