### ISSUE TITLE
RFP: komorebi -- Animated Wallpapers for Linux(linux下的动态壁纸)

### ISSUE THREAD

**Issue by Z-Y00** [debiancn/repo#156]
* 包名 : komorebi
* 主页 : https://github.com/cheesecakeufo/komorebi
* 协议 : GPLv3+ 
  语言 : vala
  简介 : Animated Wallpapers for Linux(linux下的动态壁纸)，详见上面的github链接

**Comment by hosiet** [comment]
这个软件主体都安装在 `/System/Resources/` 下面了，非常 Mac 风格；欢迎补丁来修改文件安装目录

**Comment by Yanhao** [comment]
done
