### ISSUE TITLE
RFP: nodejs-lts

### ISSUE THREAD

**Issue by eatradish** [debiancn/repo#157]
* 包名 : nodejs-lts
  版本 : 10.14-1
  作者 : 
* 主页 : https://nodejs.org/zh-cn/
* 协议 : MIT
  语言: js
  简介 : 
简介 : debian 官方仓库没有，上游提供了个 deb 软件仓库，希望 debiancn 能合并

**Comment by Yanhao** [comment]
地址 https://deb.nodesource.com/node_11.x/pool/main/n/nodejs/nodejs_11.6.0-1nodesource1_amd64.deb

**Comment by Yanhao** [comment]
done 有的时候更新不及时的话希望能及时提醒。

**Comment by Yanhao** [comment]
啊，不对，回错了，这个是最新版不是lts版。因为node官方提供的安装包lts版和最新版用的是一样的名字，所以现在只添加了最新版到社区源。
