### ISSUE TITLE
RFP: ydcv

### ISSUE THREAD

**Issue by eatradish** [debiancn/repo#171]
* 包名 : ydcv
  版本 : 0.6.1
  作者 : felixonmars
* 主页 : https://github.com/felixonmars/ydcv
* 协议 : GPLv3
  语言 : Python 2.7+
  简介 : 实用词典工具

**Comment by hosiet** [comment]
根据主页的说法，有道词典的 API 现在按量收费，软件的前景很不明确啊（

**Comment by eatradish** [comment]
确实（

**Comment by eatradish** [comment]
@hosiet 
https://github.com/quininer/x11-clipboard/pull/12

**Comment by cdluminate** [comment]
ydcv依赖互联网服务，即便license是GPL，也只能进contrib。打包难度为入门级，想要这个包的话自己动手也能10分钟内搞定。

**Comment by hosiet** [comment]
原仓库已停止开发并存档，现不考虑打包。
