### ISSUE TITLE
这个readme，写的不知所云。我就想装个软件而已。

### ISSUE THREAD

**Issue by YinGithub** [debiancn/repo#173]
// 这个模板适用于 RFP。若不是，删除即可。
// 标题：RFP: <软件包名>
// 请尽可能填完所有信息（但不是必须）。提交时请删除每行 // 后内容。 
* 包名 : 
  版本 : 
  作者 : 
* 主页 : 
* 协议 : GPLv2+ / GPLv3+ / BSD / 专有
  语言 : C / C++ / blob  // blob=上游仅提供二进制文件
  简介 : 

// 以下填写其他描述

**Comment by yangfl** [comment]
issue不是帮助中心，使用上的问题请至 https://forums.debiancn.org 或群内咨询。
