### ISSUE TITLE
RFS: apt-nosync

### ISSUE THREAD

**Issue by cdluminate** [debiancn/repo#175]
* 包名 : apt-nosync
  版本 : 0
  作者 : 我
* 主页 : 没有
* 协议 : 再说
  语言 : shell
  简介 : 将apt和dpkg转移为基于eatmydata的wrapper脚本

可以让apt和dpkg产生肉眼可见的大幅速度提升。副作用略。

**Comment by cdluminate** [comment]
https://github.com/cdluminate/apt-nosync

**Comment by cdluminate** [comment]
0.1 has been released https://github.com/cdluminate/apt-nosync/releases

**Comment by Yanhao** [comment]
done
