### ISSUE TITLE
[坑] DUPR 格式是否有助于减小DebianCN的ITP/维护工作量?

### ISSUE THREAD

**Issue by cdluminate** [debiancn/repo#178]
DUPR (以后名字可能会改）包含两种异常简单的平文本格式，意图在将整个debian目录压到一个文件中。具体的工具包和模板在这里：https://github.com/dupr/duprkit， 相应的一些实际例子在这里：https://github.com/dupr/DefaultCollection

**Comment by cdluminate** [comment]
虽然DUPR是那种像AUR的packaging-script-only分发方式，不过将产生的.deb包传到debiancn也完全没有问题。

**Comment by wi24rd** [comment]
从 mpr [1] 偷 PKGBUILD 用 makedeb [2] 构建。
类似现在的 archlinuxcn。
[1] https://mpr.hunterwittenborn.com/
[2] https://github.com/makedeb/makedeb
