### ISSUE TITLE
RFP:请求使用vscodium替代vscode或与vscode共同存在

### ISSUE THREAD

**Issue by yachen4ever** [debiancn/repo#179]
* 包名 : vscodium
  版本 :  1.33.1
  作者 :  Microsoft/VSCodium
* 主页 :  https://vscodium.github.io
             https://github.com/VSCodium/vscodium
* 协议 : MIT
  语言 : Javascript
  简介 :  微软提供的二进制vscode安装包并不由开源代码编译而来，而是加入了遥测等专有代码。VSCodium直接由vscode开源代码编译而来，其实际使用完全相同，且更符合vscode开源的身份。

**Comment by Yanhao** [comment]
源里有vscodium啊，你直接装就好了。如果版本outdated了欢迎随时提issue，不过我更新的很及时，放心。

**Comment by yachen4ever** [comment]
但是我用apt装找不到这个包啊。我的系统是debian 9,64位的。是不是这个包没有给9提供？

**Comment by yachen4ever** [comment]
我在https://repo.debiancn.org/dists/stretch/main/binary-amd64/Packages中没有找到code和vscodium，但在https://repo.debiancn.org/dists/buster/main/binary-amd64/Packages中有。确实是给Debian10打包了9没有。

**Comment by Yanhao** [comment]
deibancn现在主要提供的是对sid和testing的支持，对stable的支持有限。

**Comment by yachen4ever** [comment]
stable都不考虑支持吗。。用Debian的人多数还是会用stable而不是testing吧。希望能多支持下stable，谢谢啦
