### ISSUE TITLE
 百度云linux

### ISSUE THREAD

**Issue by levinit** [debiancn/repo#185]
* 包名 :baidunetdisk 
  版本 : 3.0.1
  作者 : baidu
* 主页 : https://pan.baidu.com/download#linux
* 协议 : 专有
  语言 : 上游仅提供二进制文件
  简介 :  百度云linux，提供deb包

debiancn还“活着”吗？

**Comment by coslyk** [comment]
这个源貌似年久失修了。。。
我搞了个 [debianzh](https://github.com/coslyk/debianzh-repo) 库，使用自动化脚本来构建和维护，你有没有兴趣提交到这里来 ：）
