### ISSUE TITLE
RFP: marktext

### ISSUE THREAD

**Issue by ocian** [debiancn/repo#187]
* 包名 : marktext
  版本 : 0.16.3
  作者 : 
* 主页 : https://github.com/marktext/marktext
* 协议 : MIT
  语言 : JavaScript / blob
  简介 : markdown 编辑器，特点是快捷键好用，界面的突出编辑内容

我会喜欢 js 写的东西，electron 降低了美观的界面和易用的操作的实现难度

**Comment by alim0x** [comment]
已添加到 repo。目前直接使用上游的 deb 包。
