### ISSUE TITLE
Conflicting Distribution: https://repo.debiancn.org testing InRelease (expected testing but got bullseye)

### ISSUE THREAD

**Issue by LoadCursor** [debiancn/repo#189]
拷贝主页的启用社区源命令，输入终端后，于各个软件包下载并安装完成后报错：Conflicting Distribution: https://repo.debiancn.org testing InRelease (expected testing but got bullseye) 不知道这个bullseye是怎么回事。谢谢！

以下为报错文本：
Get:2 https://repo.debiancn.org testing InRelease [7,555 B]       
Get:1 http://mirrors.neusoft.edu.cn/kali kali-rolling InRelease [30.5 kB]
Get:3 http://mirrors.neusoft.edu.cn/kali kali-rolling/main amd64 Packages [17.9 MB]
Get:4 https://repo.debiancn.org testing/main amd64 Packages [116 kB]
Get:5 http://mirrors.neusoft.edu.cn/kali kali-rolling/main amd64 Contents (deb) [40.3 MB]                                                                                                                                                   
Get:6 http://mirrors.neusoft.edu.cn/kali kali-rolling/contrib amd64 Packages [108 kB]                                                                                                                                                       
Get:7 http://mirrors.neusoft.edu.cn/kali kali-rolling/non-free amd64 Packages [203 kB]                                                                                                                                                      
Get:8 http://mirrors.neusoft.edu.cn/kali kali-rolling/non-free amd64 Contents (deb) [955 kB]                                                                                                                                                
Fetched 59.6 MB in 5min 57s (167 kB/s)                                                                                                                                                                                                      
Reading package lists... Done
W: Conflicting distribution: https://repo.debiancn.org testing InRelease (expected testing but got bullseye)

**Comment by hosiet** [comment]
已去除 testing 仓库，请使用发行代号名（buster, bullseye, bookworm）而非 stable/testing/unstable。
