### ISSUE TITLE
调研使用 Travis CI 打包的可能性

### ISSUE THREAD

**Issue by hosiet** [debiancn/repo#21]
持续集成系统免费的带宽/硬盘/CPU，不用白不用。应当考虑直接在持续集成编译后上传成果软件包的可能性。

**Comment by hipkomh** [comment]
用debian sid四年啦，一直看着贴吧。最近工作做了ci的东西，有我能帮忙的么

**Comment by YanhaoMo** [comment]
@hipkomh 当然, 如果有时间的话非常欢迎加入来帮忙, 可以考虑帮忙打包或者开发.
 我们的日常讨论在tg, irc和 irc.debiancn.org 这些地方, 当然这几个地方的消息都是互通的, 有时间的话也欢迎加入讨论.
如果有疑问的话欢迎通过上面的IM方式, issues, 或者论坛的[社区建设板块](https://forums.debiancn.org/c/19-category)提出, 我看到会尽快回答.

**Comment by hipkomh** [comment]
@YanhaoMo 啊噢，debian-cn的irc我常年挂着的，只是不常发言。

**Comment by YanhaoMo** [comment]
@hipkomh 哈哈, 原来你都知道了, 那么要不要领几个包呢😬

**Comment by hipkomh** [comment]
@YanhaoMo 必须的，最近在换工作，等过几天安顿下来~

**Comment by hosiet** [comment]
这个方案现在看来感觉可行性不大，因为有了新机器，所以可以直接在机器上打包。
