### ISSUE TITLE
Debian 8.5 jessie shadowsocks-libev包（包含服务端和客户端） RFS

### ISSUE THREAD

**Issue by supvesonico** [debiancn/repo#23]
通过git源码构建完成，请求上传

**Comment by YanhaoMo** [comment]
@supvesonico 😳 咦，这个包源里已经有了啊 https://github.com/debiancn/repo/issues/16

**Comment by YanhaoMo** [comment]
dup, close

**Comment by hosiet** [comment]
@YanhaoMo 等一下，新版有从 unstable 移到 Jessie 吗？为啥我这里还可以在 unstable 下找到为 Jessie 做的包？

**Comment by YanhaoMo** [comment]
@hosiet 没有啊，jessie的包在stable-experimental里应该是 https://github.com/debiancn/repo/issues/16 下的包, experimental里应该是没有这个包的啊

**Comment by YanhaoMo** [comment]
@YanhaoMo wait， 果然有，可能是我忘记移除了，马上好
