### ISSUE TITLE
RFS:libpng12/1.2.54-6

### ISSUE THREAD

**Issue by hosiet** [debiancn/repo#24]
如题。libpng12 现在使用的是 jessie-updates 中的软件包，该软件包并未针对 stretch / sid 编译。本包直接从 snapshot.debian.org 抽出，具有更新版本的 libpng12，应该会有所改进。

适用 Debian 版本：stretch / sid
二进制包/源码包存放位置：https://hosiet.me/_downloads/test/libpng12/
Git 仓库位置：N/A

**Comment by YanhaoMo** [comment]
check
