### ISSUE TITLE
考虑对源结构的重构与优化

### ISSUE THREAD

**Issue by hosiet** [debiancn/repo#26]
如题。鉴于 Debian 多版本共存的现状以及 testing 迁移的特性，应当开始考虑对现有源名称进行改造与优化。

现在有三个源：
- stable-experimental
- experimental
- unstable

这三个名字不便记忆，在新版本发布时也不便迁移。例如 Debian 9 发布时，stable 的意义已经改变，需要用户手动调整。

我的建议是以后均使用固定代号指代源仓库。例如，留三个仓库：
- jessie
- stretch
- unstable

这三个名字永远不会因为新版本发布而改变意义。新的 testing 发布后，应当采用新的代号建立第四个源。而且这几个名字与当前名字也没有冲突，可以无缝迁移。

我个人认为不需要 experimental 之类的名称。没有人会有心思测试的，上线后测试也不迟。

testing 和 Sid 的名字可以考虑用软链接的方式处理。

**Comment by hosiet** [comment]
@hosiet 实际上 unstable 和 sid 都可以作为 stretch 的别名，最终只需要设立两个源。

**Comment by YanhaoMo** [comment]
新版本发布时如果采用新的代号建立新的源，这个过程会不会时间太紧，太麻烦了，而且新版本冻结直到发布的这段时间testing和unstable之间的差异会越来越大，不如在新版本冻结的时候开始慢慢建立以新代号命名的源，在新版本发布一段时间之后放弃old-stable的维护

**Comment by hosiet** [comment]
新版两年发一回，两年动手一次，根本不麻烦吧→_→

Yanhao Mo <notifications@github.com>于2016年11月28日周一 22:10写道：

**Comment by YanhaoMo** [comment]
@hosiet 主要是 1.新版本发布时再进行创建新源的操作，时间紧 2.testing和unstable差异越来越大，那个时候两个版本可能无法很好的共用一个源

**Comment by hosiet** [comment]
@YanhaoMo 冻结以后以后再建都可以嘛，反正时间差有几个月

**Comment by YanhaoMo** [comment]
@hosiet 嘛，我的意思就是冻结以后建🌚

**Comment by alim0x** [comment]
由于 aptly 对同一仓库的多 distribution 支持不佳，是否考虑不使用 `testing` `sid`，而只使用代号，避免 `apt` 更新提示的警告带来的困惑

**Comment by hosiet** [comment]
@alim0x 在 aptly 里完全放弃 testing / sid，只在部署部分目录软链接：testing -> stretch, unstable -> sid，不知可否？这样 aptly 就完全不涉及 warning 了。

**Comment by hosiet** [comment]
@hosiet 哦刚才没看清，警告信息是用户 apt 出现的；这样来看的话可以考虑。不知道官方的实现是否可参考？虽然官方不是 aptly，但官方那里很可能内容相同。

**Comment by hosiet** [comment]
现在除了 warning 问题以外，其它都做好了；warning 不是大问题，先这样用吧。
