### ISSUE TITLE
RFS: cutegram (transition for libqt5keychain)

### ISSUE THREAD

**Issue by hosiet** [debiancn/repo#28]
由于 libqt5keychains 跳了 SONAME，原先构建的 cutegram 即将无法继续正常运行，故针对 qt5keychains-dev 重新进行了构建。目前合适的版本如下：

* cutegram [2.9.5-1aseman-xenial+git20161016.0.08f836ce-1](https://buildd.debiancn.org/repositories/test/pool/main/c/cutegram/cutegram_2.9.5-1aseman-xenial+git20161016.0.08f836ce-1.dsc)
* asemantools [1.0.0-7aseman-xenial+git20161017.0.34d8ed8a-1](https://buildd.debiancn.org/repositories/test/pool/main/a/asemantools/asemantools_1.0.0-7aseman-xenial+git20161017.0.34d8ed8a-1.dsc)
* libqtelegram-ae [1.0.0-2aseman1.1-xenial-1+git20161017.0.cad9b5de-1~testSID+1](https://buildd.debiancn.org/repositories/test/pool/main/libq/libqtelegram-ae/libqtelegram-ae_1.0.0-2aseman1.1-xenial-1+git20161017.0.cad9b5de-1~testSID+1.dsc)
* telegramqml [2.0.0-1aseman-xenial+git20161008.0.df762d76-1~testSID+1](https://buildd.debiancn.org/repositories/test/pool/main/t/telegramqml/telegramqml_2.0.0-1aseman-xenial+git20161008.0.df762d76-1~testSID+1.dsc)

更新前的注意事项：

* 注意版本号；
* 请在 libqt5keychains1 进入 testing 后再进行更新；
* 建议在更新入源之前先将源内已有 cutegram 相关软件的旧版本全部移除。

**Comment by YanhaoMo** [comment]
@hosiet 估计要等到下一周了哦，晚上的飞机，接下来一周都不在国内 = =

**Comment by hosiet** [comment]
ping

这个处理了就可以保证 debris 全部正常构建了

**Comment by YanhaoMo** [comment]
抱歉这条处理晚了 - -
以上链接都失效了

**Comment by hosiet** [comment]
没失效啊，都好着呢

**Comment by YanhaoMo** [comment]
是我这边网络的问题，解析不到buildd的dns了..

**Comment by hosiet** [comment]
done.
