### ISSUE TITLE
DEBIAN7如何使用？

### ISSUE THREAD

**Issue by redapple0204** [debiancn/repo#29]
能用debian8的办法吗？

**Comment by hosiet** [comment]
不能，需要具体软件具体分析。

redapple0204 <notifications@github.com>于2016年11月5日周六 14:52写道：

**Comment by redapple0204** [comment]
@hosiet 例如？

**Comment by hosiet** [comment]
@redapple0204 暂时没有例子，由于我不用 Debian 7 所以没有移植软件的计划。如果你需要什么软件，可以单独提出然后分析分析可能性。

**Comment by redapple0204** [comment]
@hosiet 例如：网易云音乐
这个东西在debian7上缺依赖

**Comment by hosiet** [comment]
@redapple0204 这个网易本来也没有提供合适的版本，作为闭源软件下游也无法处理。可以试试官方提供的 Ubuntu 14.04 的版本能否使用。不过出问题的可能不小。

**Comment by redapple0204** [comment]
@hosiet ubuntu14也是一样.....
好吧，谢谢了。我滚成testing好了
