### ISSUE TITLE
deepin 系列软件移植追踪说明

### ISSUE THREAD

**Issue by hosiet** [debiancn/repo#31]
### 2017-09 更新

Deepin 的软件正在官方的 [pkg-deepin-devel](https://lists.alioth.debian.org/pipermail/pkg-deepin-devel/) 组下进行打包，下面的内容已经过时。

打包中遇到的临时性依赖的软件包会在社区源 unstable 下面做暂时性的打包，一旦进入官方源则予以移除。

### 总述

社区软件源可以选择 deepin 的软件作为工作方向*之一*。原因如下：

* deepin 已经基于 Debian 开发，移植难度较小；
* 可以利用现成的构建脚本，无需从头开始，可减轻工作量；
* deepin 中某些软件较为实用，移植工作具有实际价值；
* debiancn 社区内有 deepin 员工，方便进行问题排查与汇报；

工作的最终目标可以是将整个 DDE 的用户体验移植到 Debian unstable 以及2017年将要发布的 Debian 9 平台上，同时提升打包质量，向 Debian 官方软件包的要求靠拢（但不强求）。故在本 issue 中具体追踪移植进展。

欢迎任何感兴趣的朋友参与移植工作！

----------------------------------------------------------

### 工作流程

1. 寻找到想要的 deepin 软件
2. （如果有编辑权限）直接编辑内容并在下面添加对应软件包及其依赖软件包（特指 deepin 独有的依赖软件）的信息；（如果没有编辑权限）回复本 issue 并附上信息（软件名、期望工作版本与简述），由他人代为更新信息；
3. 工作完成后，回复本 issue 并附上源码包获取方式（必须）、数字签名（可选）、二进制 deb 包获取方式（可选）及工作 Git 仓库位置（可选）；
4. 确认软件可用并进源后，编辑本 issue 并在 issue 和 README 文件中添加维护者信息。

对于非 deepin 系软件，请新开一个 issue 处理软件添加/修改问题；流程也可参考上述文字。

### 软件包追踪

按照目标进行分类，前者为工作目标（实际可用的软件），之后分列的软件包为其依赖。欢迎添加、认领、贡献软件包！

#### 目标软件
- [X] `deepin-terminal`
  + 维护者：@hosiet
- [ ] `deepin-image-viewer`
  + 打包者：@hosiet
  + [X] 重构建工作
- [ ] `deepin-movie`
  + 打包者：@mdrights
  + [ ] 重构建工作

在这里添加感兴趣的 deepin 软件……

#### 依赖软件包
- [X] `deepin-menu`
  + 维护者：@hosiet
- [X] `deepin-gettext-tools`
  + 打包者：@hosiet
  + [X] 重构建工作
- [ ] `deepin-qml-widgets`
  + 打包者：@hosiet
  + [X] 重构建工作
- [X] `deepin-tool-kit`
  + 打包者：@hosiet
- [X] `deepin-qt5integration`
  + 打包者：@hosiet

#### 说明

* 重构建：确保源码包可以在当前 Debian unstable / testing 环境下编译通过
* 打包者：软件未进入社区源之前进行工作的人员
* 维护者：已经进入社区源后维护软件的人员

### 工作小建议

* 可尝试直接从`http://mirrors.deepin.com/deepin/pool/main/d/`目录下寻找软件源码包，下载到本地尝试编译与修改；
* 可尝试从`https://github.com/linuxdeepin/`团队下面获取最新的源代码，与 Git 相结合进行打包；
* 可尝试借用 Arch Linux 社区现有打包成果，使用 `https://www.archlinux.org/packages/`直观查找软件包及其依赖关系（注意 deepin 声明的依赖与 Arch Linux 仓库内对应软件的依赖可能有所不同）；

**Comment by mdrights** [comment]
感谢@hosiet和各位的指引^_^
我尝试打包 deepin-movie 吧，多多指教。（可能本周末开始

**Comment by mdrights** [comment]
手机操作，不知如何编辑这个issue...

**Comment by ragrok** [comment]
@mdrights @hosiet 我在CSDN上看了几篇打包的文章，发现一下子还是没法掌握，我的邮箱是ragrok.lee@hotmail.com 能传授点经验么？

**Comment by hosiet** [comment]
https://www.debian.org/doc/manuals/maint-guide/index.zh-cn.html

https://hosiet.me/blog/2016/09/15/make-debian-package-with-git-the-canonical-way/

**Comment by ragrok** [comment]
谢谢。[😁]

________________________________

**Comment by ragrok** [comment]
昨天看了你写的文章，在重命名branch的时候，我翻看你打包deepin-terminal的仓库，有四个分支，upstream是从原来仓库的master分支上改过来的，那其他几个分支呢？是从对应的devloper分支重命名还是在master上分出来的？

________________________________

**Comment by hosiet** [comment]
是我当时在上游源代码上做修改时用到的，不必在意。建议你拿一个 Git 可视化工具（例如 gitk / gitg / qgit）看看分支情况就容易明白了。

Ragrok Lee <notifications@github.com>于2016年11月16日周三 14:19写道：

**Comment by hosiet** [comment]
现在主要工作转移至了 Debian 官方的的 [pkg-deepin](http://alioth.debian.org/projects/pkg-deepin/) 项目下，社区源会作为打包的测试临时仓库，一旦进入官方源则将对应软件包移除。

**Comment by anthonyfok** [comment]
Debian 从 Alioth 迁移至 Salsa 后，[pkg-deepin](https://salsa.debian.org/pkg-deepin-team) 项目的网址现为 https://salsa.debian.org/pkg-deepin-team
