### ISSUE TITLE
#请给Jessie也加入chrome和telegram，毕竟稳定版嘛

### ISSUE THREAD

**Issue by arisskz6** [debiancn/repo#34]
看到社区软件源列表里大多是对unstable打包的，jessie的好少，连chrome和telegram都没有，虽然也自己也能装上，但是感觉就是不太正统QAQ，人家Arch的aur里好多软件啊。。。虽然我还是喜欢Debian= =

**Comment by YanhaoMo** [comment]
好的，我尽快把这些软件入库 :）

**Comment by arisskz6** [comment]
哇，管理员大大反应好快。

**Comment by YanhaoMo** [comment]
@arisskz6 么么哒～

**Comment by YanhaoMo** [comment]
check
