### ISSUE TITLE
设立社区镜像源

### ISSUE THREAD

**Issue by alim0x** [debiancn/repo#38]
可行的方案有通过 VPS 同步镜像源，然后通过对象存储服务分发

参考工具：https://www.aptly.info/

**Comment by hosiet** [comment]
给几个其他的方式：
* 使用 reprepro（类似 aptly）
    优点：不需要额外软件
    缺点：无法保证事务一致性
* 在社区源原始机器上开 rsync
    优点：有通用性，未来可以扩展到其他镜像站上
   缺点：需要在原始机器上额外开 rsync 服务

我个人推荐 rsync。正规（

Mo <notifications@github.com>于2016年11月22日周二 16:31写道：

**Comment by alim0x** [comment]
我以为社区要搞 Debian 镜像站了... 社区软件源的话就不需要这么折腾了
