### ISSUE TITLE
RM: nixnote2, (lib)qevercloud

### ISSUE THREAD

**Issue by hosiet** [debiancn/repo#39]
这些软件已经进入了 Debian 官方源，应当从社区源内移除。

* qevercloud 对应的五个软件包随时应当移除；
* nixnote2 应当等待进入 testing 后进行移除。（见 https://tracker.debian.org/pkg/nixnote2）

**Comment by hosiet** [comment]
还有残留文件：

http://repo.debiancn.org/pool/main/q/qevercloud/

http://repo.debiancn.org/pool/main/n/nixnote2/

**Comment by YanhaoMo** [comment]
check
