### ISSUE TITLE
ITP: wine-gecko

### ISSUE THREAD

**Issue by hosiet** [debiancn/repo#4]
wine 没有 Gecko，连[WinRAR](http://rarlab.com)都装不上。Ubuntu 官方源也只有 2.21 版，实在过旧。

希望能够打包 wine-gecko。需要继续深入研究。

**Comment by hosiet** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=814350

**Comment by YanhaoMo** [comment]
stable 上有个2.24 也是比较旧

**Comment by YanhaoMo** [comment]
https://packages.debian.org/search?suite=all&searchon=sourcenames&keywords=wine-gecko

**Comment by hosiet** [comment]
暂时使用上游的二进制包进行提供。
