### ISSUE TITLE
RFS: seafile

### ISSUE THREAD

**Issue by alim0x** [debiancn/repo#46]
源码：

https://github.com/haiwen/seafile-client

所在 repo 已有 debian 目录

**Comment by alim0x** [comment]
已打包，测试安装使用正常，文件：

[Dropbox](https://www.dropbox.com/sh/hy3p32g6qwdeewo/AAD43mmQuLyu_GedRbks55FDa?dl=0)

**Comment by hosiet** [comment]
辛苦了。不过，请先吃下这些 lintian 检查警告和错误。
[lintian.txt](https://github.com/debiancn/repo/files/657220/lintian.txt)

**Comment by hosiet** [comment]
> seafile-gui-6.0.1/debian/rules

export 写在 Makefile 目标里是起不了作用的。请写在外部（Makefile顶部顶头写，前面不加制表符），例如：

```Makefile
#!/usr/bin/make -f
# -*- makefile -*-

export QT_SELECT := 5

%:
[TAB] dh $@ ...
```

**Comment by hosiet** [comment]
> seafile-gui-6.0.1/debian/copyright

实际上这里行首空格多了一个，缩进只需要一个空格就可以了。
其它包同理。

> seafile-gui-6.0.1/debian/seafile-gui.docs

考虑在这个文件里加上`README.md`。

> seafile-gui-6.0.1/

一堆语法错误，请向上游提交PR：
```bash
$ codespell --quiet-level=3
./Doxyfile.in:1640: refered  ==> referred
./third_party/QtAwesome/QtAwesome.cpp:567: adn  ==> and
./third_party/QtAwesome/QtAwesome.cpp:675: transfered  ==> transferred
./third_party/QtAwesome/QtAwesome.cpp:708: usefull  ==> useful
./extensions/README.org:77: enviroment  ==> environment
./extensions/context-menu.cpp:268: seperate  ==> separate
./extensions/context-menu.cpp:286: seperate  ==> separate
./debian/changelog:48: responisble  ==> responsible
./scripts/build_breakpad.sh:33: successfuly  ==> successfully
./scripts/build.py:118: frome  ==> from
...
```

> seafile-gui-6.0.1/debian/control
```
http://seafile.com -> https://www.seafile.com
```
* debhelper 7 => 10, `debian/compat` 7 => 10
* Standards-Version 3.9.5 => 3.9.8
* drop -dbg packages
其它包同理。

> seafile-daemon-6.0.1/debian/docs
空文件。考虑添加`README.markdown`。

> seafile-daemon-6.0.1/debian/*.install
完全忘记了Multi-Arch的问题，试着改改吧

>seafile-daemon-6.0.1/debian/rules
各种自己写的`dh-strip`，不好。请在所有地方删除任何与`-dbg`包相关的信息再测试一下，应该会自动生成`-dbgsym`包。其它包同理。

>seafile-daemon-6.0.1/docs
这么多文档都没出现在deb包里，不好。请查阅`dh_install`、`dh_installman`和`dh_installdocs`的用法。

>ccnet-6.0.1/debian/*.install
Multi-Arch问题。见上。

最后，那一堆 symbol 文件能维护吗？不能维护的话可以考虑直接扔掉。

**Comment by alim0x** [comment]
一下子四个包还真有点吃不消，我会找时间按照上面的信息一个一个来

**Comment by YanhaoMo** [comment]
@alim0x 加油小伙子😬

**Comment by alim0x** [comment]
seafile 四个包已有两个进入官方源 unstable，都是新打包进入的，可以关闭这个 issue 了

https://tracker.debian.org/pkg/libsearpc
https://tracker.debian.org/pkg/ccnet

**Comment by hosiet** [comment]
@alim0x https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=698681

事情没完，离冻结没几天了，可以看看四个包究竟能有几个进入源内，如果来不及的话放这里也不迟，时间点是12月25日

**Comment by hosiet** [comment]
情况已经明了，两个已进源，两个卡在 NEW 队列。之后等 backports 比较好。
