### ISSUE TITLE
RFP 为知笔记

### ISSUE THREAD

**Issue by lishoujun** [debiancn/repo#47]
为知笔记是一个非常优秀的笔记软件，拥有跨平台客户端
代码见：
https://github.com/WizTeam/WizQTClient
比较活跃，8天内有代码更新。

**Comment by yangfl** [comment]
依赖收费服务且无免费版本，倾向不主动打包

**Comment by lishoujun** [comment]
@yangfl    是的  但是我添加这个issue的时候，他家免费服务还是很好的。
人家有盈利压力。哎
