### ISSUE TITLE
RFS：sun-jdk

### ISSUE THREAD

**Issue by ilovesusu** [debiancn/repo#48]
如题，对Sun jdk进行打包

适合版本：理论上都适合，默认 stretch / sid 暂时提供amd64
二进制包：[二进制包](https://www.dropbox.com/sh/po80q15delamow6/AAByuSEDqx_pZsd5OK5EAUFva?dl=0)
Git 仓库：N/A

**Comment by YanhaoMo** [comment]
@ilovesusu @hosiet 有没有时间给检查一下～😁

**Comment by hosiet** [comment]
@YanhaoMo 今天没有时间，再找时间🌚

**Comment by YanhaoMo** [comment]
@hosiet 好的不着急😘

**Comment by hosiet** [comment]
没什么可检查的，这是自动生成的包。参考资料: https://wiki.debian.org/Java/Sun
ok

**Comment by hosiet** [comment]
done.
