### ISSUE TITLE
readme.md “开源”的说法儿改成 dfsg

### ISSUE THREAD

**Issue by insulsa** [debiancn/repo#49]
“开源”的所指，各有个的说法儿。不如以 dfsg 作为界定标准。也方便作为能不能向 debian 公式软件源迁移合并的参考。

**Comment by hosiet** [comment]
然而社区软件源里有不满足 DFSG 的开源软件，也有闭源软件，只限制 DFSG 的话也许直接往官方源放比较好。

而且开源/闭源这里指能否获取源代码，实际上能否获取源代码的区别非常大，打包处理上也不一样，相比之下 DFSG 与否在打包与软件管理上并无区分。所以个人认为这样分类有其价值。
