### ISSUE TITLE
对 stretch 和 sid 仓库进行分割

### ISSUE THREAD

**Issue by hosiet** [debiancn/repo#70]
冻结在即，两个仓库的内容已经开始发生差异。分割仓库的时候已经到了。

* [x] 建立 buster 仓库，将 unstable/sid 指向 buster
* [ ] 对 stretch 仓库内软件进行重构建
* [ ] 对 buster 仓库进行重构建

以上工作应当在 stretch 发布前完成。

**Comment by hosiet** [comment]
分割初步完成，使用了 `aptly repo copy` 功能。重构建待后续进行。

**Comment by hipkomh** [comment]
最近会报警告，W: 冲突的发行版：https://repo.debiancn.org sid InRelease (期望 sid 但得到 buster)

**Comment by YanhaoMo** [comment]
@hipkomh 这个警告是由于sid 和testing并没有分开造成的. 为了简单,sid目前只是testing的链接而已. 如果你想去掉这个警告, 把源配置里那一项的sid改成buster就好

**Comment by hosiet** [comment]
现在来看重构建暂时没有必要，使用也基本正常，这个 issue 先关掉。
