### ISSUE TITLE
仓库软件包搜索功能

### ISSUE THREAD

**Issue by hosiet** [debiancn/repo#72]
为了在前端实现软件包搜索功能，在后端实现了提供 json 数据的相应代码。现在，在 https://repo.debiancn.org/info/ 目录下的各个 json 文件可以为前端提供所需的数据，每小时刷新一次。

文件逻辑：

* 永远有一个 `codename.json`，提供存在的发行版代号列表，例如 `stretch` 或者 `jessie`。
* 按照已有发行版代号的规律，存在一个或多个名称类似 `stretch.json` 或者 `jessie.json` 的文件，具体个数与 `codename.json` 内容一致。

* * *

现在只剩下在前端做对应的代码了。纯粹的前端的活，可能稍微有点麻烦，但绝对不复杂。

@YanhaoMo @ocian

**Comment by ocian** [comment]
详细说一下做成什么样的效果吧
甘豆腐预留的一个搜索框好像放不下这么多的内容
我可以这样设想一下
1. 那个搜索框，使用者查看有没有要找的包名，在使用者输入内容的时候，在搜索栏下面显示匹配的包名。点击出现的包名可以进入另一个页面展示给出的其他信息
2. 另一个页面，一个专门的搜索用页面，在搜索框没有输入内容的时候点击搜索按钮会直接进入这个页面并且显示软件包列表。在输入内容的时候在这个页面显示详细的软件包信息。在这个页面的上面放一个一样的搜索框。  这里可以做一个要不要进入搜索页面的提示。
3. 这样其实也不麻烦，但是还是没有解决手机的兼容问题，我发现 debian 网站， slackware 的镜像下载页，好像都改过 类似 autoindex 功能生成的页面，但是我对后端完全不了解，请问有没有从这方面入手的经验或者其他人的指导可以参考呢？我这一块应该可以说没什么基础，nginx的文档不怎么看得懂，

**Comment by ocian** [comment]
搜索功能做出来了， 现在只显示了匹配的包名，并且没有任何跳转。 后续加一个专门的搜索页面。

**Comment by hosiet** [comment]
@ocian 做出来了？代码呢？使用方法呢？

**Comment by ocian** [comment]
分支 iss#10 ，clone之后，header.html的 搜索框可以显示输入内容的匹配包名，包括键盘输入和粘贴
我觉得有必要做一个单独的搜索页，做成类似官方软件仓的形式
还有一个问题，autoindex我不会用，不知道要怎么修改这个功能的生成页，有没有实现可以参考？

**Comment by hosiet** [comment]
现在的情况是，所有 nginx 提供的网页都会自动添加头部和尾部，单独的页面没法做。如果要修改这一点，必须修改主机 nginx 配置。

在这种情况下，除了单独页面的做法以外，还有一种方式是做所谓的“单页应用”，即页内用 JS 显示用户选择的详细信息。这样可以避免不同页面的问题。

你觉得哪个好？是单独写一个与其它页面完全没关系的搜索页（没有头部也没有尾部，已有的那个搜索框失去作用，直接跳转到特定搜索页，为该特定搜索页添加 nginx 例外），还是在所有已有页面上添加 js 在页内显示信息，使用那个搜索框在页内显示信息？我个人倾向后者。

**Comment by ocian** [comment]
这两种做法对我来说是一样的，
我的问题是怎么兼容移动端，
如果我去研究PHP，或者其他服务器有环境的后端语言，可以关闭autoindex使用写出来的页面吗？
搜索页写好之后先用现在的这个搜索的功能。
我觉得GitHub也是部分目录文件可以读取的，还有可以编辑可以访问的，不会就只是一个autoindex的类似功能

**Comment by hosiet** [comment]
现在的想法是一切在前端实现，后端纯静态，只有 nginx，不要用 PHP 之类的脚本语言，因为部署会增加额外的麻烦。
GitHub 可是 ruby 全动态的，根本没有任何静态页面，思
思路和现在我们的情况完全不一样。

现在在前端写代码，可以完全不考虑 autoindex 的影响，然后看看能做出什么。

**Comment by hosiet** [comment]
现在有一个问题：搜索结果出现了重复项。在下拉菜单中，最后不要出现重复名称的软件包，在以后要实现的详细描述中再对重复情况进行处理。

**Comment by ocian** [comment]
把有关autoindex的配置放在GitHub可以吗

**Comment by hosiet** [comment]
配置真的没什么可说的，就这么几行：

```nginx
server{
        listen 80;
        server_name repo.debiancn.org;
        root /data/repo/public;
        add_before_body /.theme/header.html;
        add_after_body /.theme/footer.html;
        autoindex_exact_size off;
        autoindex on;
        autoindex_localtime on;
}
```

**Comment by ocian** [comment]
[The ngx_http_addition_module module is a filter that adds text before and after a response. ](http://nginx.org/en/docs/http/ngx_http_addition_module.html)

**Comment by ocian** [comment]
输入框获取焦点的时候下拉菜单会出现， 失去焦点的时候下拉菜单会隐藏， 没有结果的时候输入框左下角的阴影我没作处理;
重复想大概去掉了， 需要检查一下有没有bug;
最后一条你好像已经做好了。
我觉得我的方法可行，添js怎么想都比添html靠谱。
我们已经激进到开始使用flex布局了，所以ES6没什么问题吧

**Comment by hosiet** [comment]
失去焦点下拉菜单隐藏这个功能实现了吗？在哪里？GitHub 代码里好像没有。

另外用 JS 操作 DOM 当然可以，没什么问题，想怎么操作都行。不过现有的框架完全没必要移除（header.html 和 footer.html），因为真的没有必要，反正都要在头部和尾部加上 HTML 片段。在已有的 HTML 上修改，添加你想添加的 JS 代码即可。

**Comment by hosiet** [comment]
搜索功能已经完成了，于是这个 issue 可以关闭了。
