### ISSUE TITLE
[RFU] adapta gtk theme

### ISSUE THREAD

**Issue by alim0x** [debiancn/repo#75]
https://github.com/adapta-project/adapta-gtk-theme

![](https://github.com/adapta-project/adapta-github-resources/blob/master/images/Materials.png)

**Comment by alim0x** [comment]
3.89.4.138 - 2days ago

**Comment by hosiet** [comment]
done

https://repo.debiancn.org/pool/main/a/adapta-gtk-theme/adapta-gtk-theme_3.89.4.142-1_all.deb

**Comment by simonsmh** [comment]
@hosiet 这个编译带额外的参数么？chrome tg之类的

**Comment by hosiet** [comment]
参数见此: https://github.com/hosiet/Adapta/blob/master/debian/rules

--with-telegram 连文档也没有，所以这种 WIP 的功能没加。

**Comment by Alexmitter** [comment]
@hosiet i wait for you to give me a okay, maybe you need to fix something else

**Comment by hosiet** [comment]
@Alexmitter What do you mean for "fixing"? If there are something wrong with the package, please open an issue for it.
