### ISSUE TITLE
[RFU]: ttyd/1.3.2

### ISSUE THREAD

**Issue by simonsmh** [debiancn/repo#77]
https://github.com/tsl0922/ttyd/commit/f60398fb0976d5a682f2a28c2e8f8b90ec1c4c2c

https://github.com/tsl0922/ttyd/issues/33
Libwebsockets 需要重新编译以适用ttyd部分特性

**Comment by hosiet** [comment]
done

请协助测试软件包可用性。

**Comment by hosiet** [comment]
libwebsockets 请新开 issue。
