### ISSUE TITLE
ITP: pytorch -- Tensors and Dynamic neural networks in Python  with strong GPU acceleration.

### ISSUE THREAD

**Issue by CDLuminate** [debiancn/repo#80]
```
如果您发现了一个适合 Debian 但无法向官方源提交的软件，您可以考虑将其加入我们的社区软件源。
```

我在上游提交了pytorch和pytorch-contrib的ITP，但是因为一些细节原因（下文会讨论）一直没有往官方源里边扔。现在看起来似乎很适合暂时放在这里。

Debian是一个Universal的OS，所以各种比较新的SIMD指令编译到二进制里边是不行的。现在上游使用了诸如AVX2这类指令及，直接编译出来显然不能进官方仓库。。。上有暂时还没有提供类似 DISABLE_SIMD 之类的编译选项，所以想在这里暂时落脚试试看。

```
    * Package name    : pytorch
      Version         : 0.1.7
      Upstream Author : (Py)Torch Developers
    * URL             : http://pytorch.org/
    * License         : BSD-3-Clause
      Programming Lang: python, cuda, c, c++
      Description     : Tensors and Dynamic neural networks in Python with strong GPU acceleration.
```
带`-contrib`后缀的是CUDA版本，属于contrib section

这里是暂时的非正式打包仓库
https://github.com/cdluminate/pytorch

这里是一种非常诡异的deb包分发方式，deb包由debomatic-amd64编译，但是没有签名
https://github.com/cdluminate/pytorch-debs

[1] ITP: pytorch -- https://bugs.debian.org/853923
[2] ITP: pytorch-contrib -- https://bugs.debian.org/853914

**Comment by hosiet** [comment]
是机器学习相关的软件呢，完成度挺高的（debomatic 都可以编译通过）。

没什么别的问题，只有一个小疑问：您愿意为源码包签名吗？愿意的话，可以将签名的源码包放进来。

**Comment by CDLuminate** [comment]
分类是 science / machine learning, deep learning

加GPG签名没有问题。不过我还没有仔细看debiancn的工作流程，不知道是否需要添加keyring之类的？

**Comment by hosiet** [comment]
Keyring 这个没关系的，这儿没有 `debian-keyring` 的等价物，暂时只用 archive keyring，源码包签名仅作参考。有源码包后暂时是 sbuild 手动构建一份二进制包并放入仓库。

**Comment by CDLuminate** [comment]
好的，也就是说，我需要做的事情是：

1. 对已经在debomatic编译好的amd64.changes进行签名
2. 分别对pytorch和pytorch-contrib在此提交一份RFS

Correct？

**Comment by hosiet** [comment]
其实 changes 文件在这里不重要，dsc 文件的签名更有意义。RFS 合在一份提交也无妨。

**Comment by CDLuminate** [comment]
谢谢。我将在不久之后完成这个ITP :-)

**Comment by CDLuminate** [comment]
lintian和source/format以后再修好了

**Comment by hosiet** [comment]
done (#81)
