### ISSUE TITLE
RFS: pytorch/0.1.12 , pytorch-contrib/0.1.12

### ISSUE THREAD

**Issue by CDLuminate** [debiancn/repo#81]
Closes: https://github.com/debiancn/repo/issues/80

https://github.com/CDLuminate/pytorch-debs/blob/master/pytorch_0.1.12~1.dsc
https://github.com/CDLuminate/pytorch-debs/blob/master/pytorch-contrib_0.1.12~1.dsc
两个dsc和对应的changes都已经签名。

**Comment by hosiet** [comment]
done (stretch)
