### ISSUE TITLE
vscode 考虑重打包

### ISSUE THREAD

**Issue by alim0x** [debiancn/repo#83]
考虑修改 `postinst` 中添加官方源的操作

**Comment by hosiet** [comment]
可以可以，有空就做吧

**Comment by alim0x** [comment]
目前的做法是 `dpkg` 解开，删除 `postinst` 中添加 key 和源的操作后压回去，不知道有没有更合适的操作方法，没有的话就这样手动处理

**Comment by YanhaoMo** [comment]
话说chrome的包是不是也需要这么处理一下，这种工作最好有脚本自动去处理。

**Comment by alim0x** [comment]
自动处理是没有问题的，如果用正则匹配的话就得保证新版的包 `postinst` 没有改动。
当然，可以在执行脚本的过程中给出提示，手工确认修改是正确的，过段时间有空我写个 vscode 的吧。

**Comment by hipkomh** [comment]
这个可以把目录统一到/opt么？参考wps的做法，官方deb包也是直接丢/opt的吧

**Comment by alim0x** [comment]
@hipkomh 社区源的 vscode 除了去掉添加官方源的操作以外没有做任何修改

**Comment by hipkomh** [comment]
@alim0x 升级了

**Comment by YanhaoMo** [comment]
@alim0x 升级了

**Comment by alim0x** [comment]
@hipkomh @YanhaoMo 已更新

**Comment by YanhaoMo** [comment]
@alim0x 这个issue可以关了吧, 重新打包的事情看起来已经解决了, 如果要跟踪自动化脚本的事情, 新开一个issue比较好
