### ISSUE TITLE
RFP：推荐几个我常用的软件

### ISSUE THREAD

**Issue by hipkomh** [debiancn/repo#86]
Franz 聊天、邮箱工具，支持微信和钉钉，有额外的插件支持更多，Devdocs强推
Pencil 画原型图的工具 
copyq 剪切板管理工具，应该是Linux下最好用的了
Enpass 密码管理器，有官方的deb源，可以考虑整合一下
metasploit-framework 也已经有deb源，可以整合进来？
IDEA  他们家的DataGrip PyCharm等一堆IDE也算普遍的需求了

**Comment by hipkomh** [comment]
这些个包我可以负责跟进管理，几位管理者看到的话拜托回复一下啦～

**Comment by hosiet** [comment]
这些软件都不是很熟悉。先明确一下是否是自由软件以及是否开源，以及上游已经提供源的软件就没必要放进来了。

其它的能从源码开始编译的尽量从源码编译即可，如果有 deb 打包脚本的话最好和源代码同时提供，形式上 github repo 或者 tarball 均可。请为每个软件单独开一个 issue 进行讨论。

**Comment by hipkomh** [comment]
ok，我整理一下
