### ISSUE TITLE
RFP：devdocs 文档查看器

### ISSUE THREAD

**Issue by hipkomh** [debiancn/repo#88]
devdocs
简介：类似mac上dash的功能，方便检索文档，源里有同类的zeal。
项目协议：MIT
项目地址：https://github.com/egoist/devdocs-desktop
deb包：https://github.com/egoist/devdocs-desktop/releases

**Comment by hosiet** [comment]
又是一个 electron 应用，真糟糕（

**Comment by hipkomh** [comment]
重新打包的话 建议修改分类 Categories=Development;

相对zeal来说，它的优点有下载速度快、检索功能更方便，gtk下显示效果更赞，缺点就是基于electron安装包很大，总体来说文档资源比zeal弱一点。
electron的应用中这个资源占用简直不能再良心了，其他的看着确实心烦。

**Comment by YanhaoMo** [comment]
@hosiet 这个RFP目前解决了么,看到已经过去好多天了

**Comment by YanhaoMo** [comment]
啊, 抱歉看到有deb包以为是RFS

**Comment by alim0x** [comment]
Done.
