### ISSUE TITLE
RFU: ttyd/1.3.3

### ISSUE THREAD

**Issue by simonsmh** [debiancn/repo#94]

**Comment by hosiet** [comment]
done (stretch, buster)

**Comment by simonsmh** [comment]
https://github.com/debiancn/repo/issues/78
emmm...

**Comment by simonsmh** [comment]
ttyd很可能需要用社区源打包的libwebsockets再次重新打包一下🤣
麻烦你了，谢谢！

**Comment by hosiet** [comment]
@simonsmh 问题由上游解决： https://tracker.debian.org/news/872953

**Comment by simonsmh** [comment]
感谢！
