### ISSUE TITLE
RFP:RStudio

### ISSUE THREAD

**Issue by Joker-Song** [debiancn/repo#96]
名称:RStudio
R语言IDE,有的 Desktop版和Server版
项目地址：https://github.com/rstudio/rstudio
下载页面：https://www.rstudio.com/products/rstudio/download/#download

**Comment by yangfl** [comment]
forwarded https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=617296

**Comment by hosiet** [comment]
考虑到上游为每个 Debian 版本都做了支持和可供下载的 deb 包，可优先使用上游提供的软件包。
