### ISSUE TITLE
RFU: deepin-tool-kit

### ISSUE THREAD

**Issue by YanhaoMo** [debiancn/repo#99]
源里的版本是0.2.6-0.1, 现在的最新版本是0.3.3
https://github.com/linuxdeepin/dtkwidget/tree/0.3.3

**Comment by hosiet** [comment]
fix blocked by https://bugs.launchpad.net/gsettings-qt/+bug/1706682

**Comment by hosiet** [comment]
deepin-tool-kit 已经被砍掉了，因此关闭这个 issue。
